### ISSUE TITLE
Failed to Compile on Windows MikTex

### ISSUE THREAD

**Issue by sturgman** [DarkBuffalo/ox-report#9] opened 2023-12-14 23:15 UTC
**Describe the bug**
Under Windows and MikTex, ox-report fails to produce PDF without errors. Depending on content, it also does not produce PDF at all. A fairly simple org document that produces a PDF with errors is:
```
#+title: Minutes
#+author: Myself
#+language: en
#+options: toc:nil
#+where: Awesome Office
#+when: <2023-12-14 Thu>
#+present: Me
#+initiator: The Boss
#+project: Pasta Committee
#+duration: 6H

* ACTIONS
 #+BEGIN: columnview :id global :match "/TODO|DONE" :format "%ITEM(What) %TAGS(Who) %DEADLINE(When) %TODO(State)"
 | What      | Who        | When | State |
 |-----------+------------+------+-------|
 | Eat Pasta | :@TheBoss: |      | TODO  |
 #+END:
* DECISIONS
 #+BEGIN: columnview :id global :match "Decision" :format "%ITEM(Decisions)"
 | Decisions  |
 |------------|
 | Bake pasta |
 #+END:

* Notes
** Bake pasta :Decision:
** TODO Eat Pasta :@TheBoss:
```

**Expected behavior**
I expect clean compilation and generation of PDF

**Screenshots**
This is the actual PDF generated.
![image](https://github.com/DarkBuffalo/ox-report/assets/4121024/426d4d41-e823-414d-bfca-be289b801720)

**Desktop (please complete the following information):**
 - Windows
 - Emacs 28.2

**Output LaTeX**
Output LaTeX attached.
[test.tex.txt](https://github.com/DarkBuffalo/ox-report/files/13679150/test.tex.txt)

**I love your template**
Hope I can make it work on my environment.

**Comment by sturgman** [comment] 2023-12-15 23:06
Identified that the output tex file has a locale of `american` for babel. I can't figure out where in the lisp code this is determined and printed. Can anyone help? Reading lisp is not an ability I currently possess.

**Comment by DarkBuffalo** [comment] 2023-12-18 19:59
hello @sturgman,

Can you transmit the result of the "Org PDF Latex Output" buffer?

**Comment by DarkBuffalo** [comment] 2023-12-18 21:03
duplicate of #10

**Comment by DarkBuffalo** [comment] 2023-12-19 17:34
hello @sturgman,

can you test with `#+language: fr` ?

**Comment by DarkBuffalo** [comment] 2023-12-19 17:41
> hello @sturgman,
> 
> Can you transmit the result of the "Org PDF Latex Output" buffer?

It's not my code that generates this. I think it's org.

**Comment by sturgman** [comment] 2023-12-20 01:52
Here is `Org PDF Latex Output`:
```
Initial Win CP for (console input, console output, system): (CP1252, CP65001, CP1252)
I changed them all to CP1252
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 6 Nov. 2023. Version 4.81.
Latexmk: Getting log file 'test.log'
Latexmk: Examining 'test.log'
Latexmk: Log file says output to 'test.pdf'
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex':  Reasons for rerun
Changed files or newly in use/created:
  test.aux
  test.tex
Category 'changed_user':
  test.tex
Category 'never_run':
  pdflatex

------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.10.12) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.
entering extended mode
(test.tex
LaTeX2e <2023-11-01>
L3 programming layer <2023-12-08>

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cl
s
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/oberdiek\ifla
ng.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/infwarerr\inf
warerr.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pdftexcmds\pd
ftexcmds.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/ltxcmds\ltxcm
ds.sty)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/setspace\setspa
ce.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphi
cx.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval
.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphi
cs.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\trig.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\gr
aphics.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-def\pd
ftex.def)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\xcolor.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\co
lor.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\mathco
lor.ltx))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\dvipsn
am.def)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/colortbl\colort
bl.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\array.sty
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\calc.sty)

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/enumitem\enumit
em.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/snotez\snotez.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolb
ox.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/pgfopts\pgfopts
.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/pgf/utilities\p
gfkeys.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pgf/utilities
\pgfkeys.code.tex
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pgf/utilities
\pgfkeyslibraryfiltered.code.tex))))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/marginnote\marg
innote.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type-pdftex.def)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/textcase\textca
se.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/booktabs\bookta
bs.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsmath
.sty
For additional information on amsmath, use the `?' option.

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amstext
.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsgen.
sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsbsy.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsopn.
sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amssym
b.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amsfon
ts.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amscls\amsthm.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/ms\multitoc.sty

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\multicol.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\ifthen.sty
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geomet
ry.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geomet
ry.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/fancyhdr\fancyh
dr.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
ge.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
ge2e.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
gemodern.sty) 
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3packages/xpar
se\xparse.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3kernel\expl3.
sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3bac
kend-pdftex.def)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\tabularx.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/carlisle\ltxtab
le.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\longtable
.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\rotati
ng.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel\babel.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel\txtbabe
l.def)
*************************************
* Local config file bblopts.cfg used
*

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/arabi\bblopts.c
fg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\a
merican.ldf
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\e
nglish.ldf)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/
en\babel-american.tex)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.st
y) (test.aux
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/
en\babel-english.tex))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/context/base/mkii\sup
p-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/epstopdf-pkg\ep
stopdf-base.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/grfext\grfext.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/kvdefinekeys\
kvdefinekeys.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/kvoptions\kvopt
ions.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/kvsetkeys\kvset
keys.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/00miktex\epstop
df-sys.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-cm
r.cfg)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\t1cmss.fd)

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsa.f
d)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-ms
a.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsb.f
d)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-ms
b.cfg)
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

Overfull \hbox (136.57321pt too wide) in paragraph at lines 287--292
$[]$

Underfull \hbox (badness 10000) in paragraph at lines 287--292

[1{C:/Users/coolusername/AppData/Local/MiKTeX/fonts/map/pdftex/pdftex.map} <./
logo.png>] 
enddocument/afterlastpage: lastpage setting LastPage.
(test.aux)

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

 )
(see the transcript file for additional information) <C:\Users\coolusername\Ap
pData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss0900.pk> <C:\Users\st
urgmancohen\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecsx1200.pk
> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi6
00\ecxc1200.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jk
nappen/ec/dpi600\ecbx1200.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\font
s/pk/ljfour/jknappen/ec/dpi600\ecrm1000.pk> <C:\Users\coolusername\AppData\Loc
al\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecbx1440.pk> <C:\Users\sturgmancoh
en\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss1000.pk> <C:\Use
rs\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss14
40.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec
/dpi600\ecsx2074.pk><C:/Users/coolusername/AppData/Local/Programs/MiKTeX/fonts
/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on test.pdf (1 page, 67836 bytes).
Transcript written on test.log.
Latexmk: Getting log file 'test.log'
Latexmk: Examining 'test.fls'
Latexmk: Examining 'test.log'
Latexmk: References changed.
Latexmk: Log file says output to 'test.pdf'
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex':  Reasons for rerun
Changed files or newly in use/created:
  test.aux

------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.10.12) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.
entering extended mode
(test.tex
LaTeX2e <2023-11-01>
L3 programming layer <2023-12-08>

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cl
s
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/oberdiek\ifla
ng.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/infwarerr\inf
warerr.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pdftexcmds\pd
ftexcmds.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/ltxcmds\ltxcm
ds.sty)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/setspace\setspa
ce.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphi
cx.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval
.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphi
cs.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\trig.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\gr
aphics.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-def\pd
ftex.def)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\xcolor.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\co
lor.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\mathco
lor.ltx))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\dvipsn
am.def)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/colortbl\colort
bl.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\array.sty
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\calc.sty)

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/enumitem\enumit
em.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/snotez\snotez.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolb
ox.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/pgfopts\pgfopts
.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/pgf/utilities\p
gfkeys.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pgf/utilities
\pgfkeys.code.tex
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/pgf/utilities
\pgfkeyslibraryfiltered.code.tex))))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/marginnote\marg
innote.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type-pdftex.def)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\micro
type.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/textcase\textca
se.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/booktabs\bookta
bs.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsmath
.sty
For additional information on amsmath, use the `?' option.

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amstext
.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsgen.
sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsbsy.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsmath\amsopn.
sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amssym
b.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\amsfon
ts.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amscls\amsthm.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/ms\multitoc.sty

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\multicol.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\ifthen.sty
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geomet
ry.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geomet
ry.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/fancyhdr\fancyh
dr.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
ge.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
ge2e.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/lastpage\lastpa
gemodern.sty) 
))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3packages/xpar
se\xparse.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3kernel\expl3.
sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3bac
kend-pdftex.def)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\tabularx.
sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/carlisle\ltxtab
le.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/tools\longtable
.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/graphics\rotati
ng.sty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel\babel.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel\txtbabe
l.def)
*************************************
* Local config file bblopts.cfg used
*

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/arabi\bblopts.c
fg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\a
merican.ldf
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\e
nglish.ldf)))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/
en\babel-american.tex)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.s
ty)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.st
y) (test.aux)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/context/base/mkii\sup
p-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/epstopdf-pkg\ep
stopdf-base.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/grfext\grfext.s
ty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/generic/kvdefinekeys\
kvdefinekeys.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/kvoptions\kvopt
ions.sty
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/kvsetkeys\kvset
keys.sty))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/00miktex\epstop
df-sys.cfg))
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-cm
r.cfg)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/base\t1cmss.fd)

(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsa.f
d)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-ms
a.cfg)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsb.f
d)
(C:\Users\coolusername\AppData\Local\Programs\MiKTeX\tex/latex/microtype\mt-ms
b.cfg)
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.288 \frontmatter
                  

Overfull \hbox (136.57321pt too wide) in paragraph at lines 287--292
$[]$

Underfull \hbox (badness 10000) in paragraph at lines 287--292

[1{C:/Users/coolusername/AppData/Local/MiKTeX/fonts/map/pdftex/pdftex.map} <./
logo.png>] 
enddocument/afterlastpage: lastpage setting LastPage.
(test.aux) )
(see the transcript file for additional information) <C:\Users\coolusername\Ap
pData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss0900.pk> <C:\Users\st
urgmancohen\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecsx1200.pk
> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi6
00\ecxc1200.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jk
nappen/ec/dpi600\ecbx1200.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\font
s/pk/ljfour/jknappen/ec/dpi600\ecrm1000.pk> <C:\Users\coolusername\AppData\Loc
al\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecbx1440.pk> <C:\Users\sturgmancoh
en\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss1000.pk> <C:\Use
rs\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec/dpi600\ecss14
40.pk> <C:\Users\coolusername\AppData\Local\MiKTeX\fonts/pk/ljfour/jknappen/ec
/dpi600\ecsx2074.pk><C:/Users/coolusername/AppData/Local/Programs/MiKTeX/fonts
/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on test.pdf (1 page, 67836 bytes).
Transcript written on test.log.
Reverting Windows console CPs to (in,out) = (1252,65001)
Latexmk: Getting log file 'test.log'
Latexmk: Examining 'test.fls'
Latexmk: Examining 'test.log'
Latexmk: Log file says output to 'test.pdf'
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'test.log' and/or above output for details

```

**Comment by DarkBuffalo** [comment] 2023-12-20 16:29
fix with https://github.com/DarkBuffalo/ox-report/commit/36e7f5e6e8cd836bbfcb0e85be01faab21f725fd

**Closed as completed by DarkBuffalo** 2023-12-20 16:29 UTC

**Comment by sturgman** [comment] 2023-12-20 22:47
Hey! Was still getting issues and no PDF produced. I fixed them by installing `cm-super`. Since cm-super does not require a `usepackage` declaration, MiKTeX does not automatically (or ask) about installing it. Not sure how to work around that but wanted to bring it up to you.

Thanks so much for the quick turnaround!

**Comment by DarkBuffalo** [comment] 2023-12-21 07:31
> Hey! Was still getting issues and no PDF produced. I fixed them by installing `cm-super`. Since cm-super does not require a `usepackage` declaration, MiKTeX does not automatically (or ask) about installing it. Not sure how to work around that but wanted to bring it up to you.
> 
> Thanks so much for the quick turnaround!

thanks for the information.  I am surprised because I invoke cm-super via '\usepackage[T1]{fontenc}' https://github.com/DarkBuffalo/ox-report/blob/36e7f5e6e8cd836bbfcb0e85be01faab21f725fd/ox-report.el#L57 and on my config miktex installs it automatically by this invocation.
